name = "HELOC Florida Theme"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "Florida HELOC education covering how home equity lines of credit work, rates, terms, and how to use HELOCs strategically for home improvements or debt consolidation."
homepage = "https://helocfl.com/"
tags = ["blog", "responsive", "Florida HELOC", "home equity"]
features = ["blog", "responsive"]
min_version = "0.100.0"

[author]
  name = "Browse LendersÂ®"
  homepage = "https://helocfl.com/"